---
- hosts: all
  user: root
  become: true
  gather_facts: false
  tasks: 
  - name: Install http
    yum: name=httpd state=present
  - name: copy index file
    copy: src=/var/www/html/index.html dest=/var/www/html/index.html owner=root group=root mode=0755
  - name: starting service
    service: name=httpd enabled=true state=started

